# Generated by Django 4.1.1 on 2022-09-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_menu_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
